import JSZip from "jszip";
import yaml from "js-yaml";

export interface UploadFile {
  file: File;
  path: string;
}

export interface MigrationOptions {
  packAuthor: string;
  packVersion: string;
  includeAssets: boolean;
}

export interface MigrationResult {
  blob: Blob;
  fileName: string;
  summary: Record<string, unknown>;
}

type AnyRecord = Record<string, any>;

const SUPPORTED_CONFIG_KEYS = new Set(["items", "font_images", "categories", "equipments"]);
const GENERATED_COMMENT = "Generated by node-web ItemsAdder single-pack migrator.";
const HANDHELD_SUFFIXES = [
  "_sword",
  "_axe",
  "_pickaxe",
  "_shovel",
  "_hoe",
  "_wand",
  "_staff",
  "_spear",
  "_knife",
  "_hammer",
  "_musket",
  "_paxel",
];

function isRecord(value: unknown): value is AnyRecord {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function normalizePath(path: string): string {
  return path.replace(/\\/g, "/").replace(/^\/+/, "").replace(/\/+/g, "/");
}

function normalizeId(value: unknown): string {
  return String(value)
    .trim()
    .replace(/\\/g, "/")
    .replace(/(\.png|\.json)$/i, "")
    .replace(/[^0-9A-Za-z_./:-]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();
}

function namespaceFromData(data: unknown, fallback: string): string {
  if (isRecord(data) && isRecord(data.info) && data.info.namespace) {
    return normalizeId(String(data.info.namespace).replace(/\//g, "_"));
  }
  return normalizeId(fallback.replace(/\//g, "_"));
}

function qualified(namespace: string, itemId: unknown): string {
  const id = normalizeId(itemId);
  return id.includes(":") ? id : `${namespace}:${id}`;
}

function vanillaMaterial(value: unknown, fallback = "paper"): string {
  if (value === undefined || value === null) {
    return fallback;
  }
  return normalizeId(value);
}

function resourceLocation(namespace: string, value: unknown, prefix?: string): string | null {
  if (value === undefined || value === null) {
    return null;
  }
  const raw = String(value).trim().replace(/\\/g, "/").replace(/(\.png|\.json)$/i, "");
  if (!raw) {
    return null;
  }
  if (raw.includes(":")) {
    const [ns, ...rest] = raw.split(":");
    return `${normalizeId(ns)}:${normalizeId(rest.join(":"))}`;
  }

  let path = normalizeId(raw);
  const knownRoots = [
    "item/",
    "block/",
    "entity/",
    "font/",
    "gui/",
    "models/",
    "textures/",
    "trims/",
    "equipment/",
  ];
  const normalizedPrefix = prefix?.replace(/\/+$/, "");
  if (
    normalizedPrefix &&
    !path.startsWith(`${normalizedPrefix}/`) &&
    !knownRoots.some((root) => path.startsWith(root))
  ) {
    path = `${normalizedPrefix}/${path}`;
  }
  return `${namespace}:${path}`;
}

function idPath(value: string): string {
  const parts = value.split(":", 2);
  return parts.length === 2 ? parts[1] : value;
}

function inferParent(material: string, itemId: string): string {
  const plainMaterial = idPath(material);
  const plainItemId = idPath(itemId);
  if (["bow", "crossbow", "fishing_rod"].includes(plainMaterial)) {
    return `minecraft:item/${plainMaterial}`;
  }
  if (["_sword", "_axe", "_pickaxe", "_shovel", "_hoe", "_trident"].some((suffix) => plainMaterial.endsWith(suffix))) {
    return "minecraft:item/handheld";
  }
  if (HANDHELD_SUFFIXES.some((suffix) => plainItemId.endsWith(suffix))) {
    return "minecraft:item/handheld";
  }
  return "minecraft:item/generated";
}

function convertText(value: unknown): unknown {
  return value ?? null;
}

function convertLore(value: unknown): unknown[] | null {
  if (value === undefined || value === null) {
    return null;
  }
  return Array.isArray(value) ? value.map(convertText) : [convertText(value)];
}

function setConverted(converted: AnyRecord, key: string, id: string, value: AnyRecord): void {
  converted[key] ??= {};
  converted[key][id] = value;
}

function mergeDictOfDicts(target: AnyRecord, key: string, values: AnyRecord): void {
  if (Object.keys(values).length === 0) {
    return;
  }
  target[key] ??= {};
  Object.assign(target[key], values);
}

function convertGeneratedModel(namespace: string, itemId: string, material: string, resource: AnyRecord): AnyRecord {
  let textures: unknown = resource.textures ?? resource.texture;
  if (typeof textures === "string") {
    textures = [textures];
  }
  const textureList: unknown[] = Array.isArray(textures) ? textures : [];
  const textureLocations = textureList
    .map((texture: unknown) => resourceLocation(namespace, texture))
    .filter((loc: string | null): loc is string => Boolean(loc));

  if (idPath(material) === "elytra" && textureLocations.length === 1) {
    return { textures: [textureLocations[0], textureLocations[0]] };
  }
  if (textureLocations.length === 1) {
    return { texture: textureLocations[0] };
  }
  if (textureLocations.length > 1) {
    return { textures: textureLocations };
  }

  const path = resourceLocation(namespace, resource.model_path) ?? resourceLocation(namespace, itemId, "item");
  return {
    model: {
      type: "minecraft:model",
      path,
      generation: {
        parent: inferParent(material, itemId),
        textures: { layer0: path },
      },
    },
  };
}

function furnitureRulesFromIa(furniture: AnyRecord): AnyRecord {
  const placeable = isRecord(furniture.placeable_on) ? furniture.placeable_on : {};
  const rules: AnyRecord = {};
  if (placeable.floor ?? true) {
    rules.ground = { rotation: "four", alignment: "center" };
  }
  if (placeable.walls) {
    rules.wall = { rotation: "any", alignment: "center" };
  }
  if (placeable.ceiling) {
    rules.ceiling = { rotation: "four", alignment: "center" };
  }
  return Object.keys(rules).length ? rules : { ground: { rotation: "four", alignment: "center" } };
}

function convertFurniture(namespace: string, itemId: string, item: AnyRecord, furniture: AnyRecord): AnyRecord {
  const ceId = qualified(namespace, itemId);
  const sound = isRecord(furniture.sound) ? furniture.sound : {};
  const settings: AnyRecord = { item: ceId };
  const sounds: AnyRecord = {};
  for (const key of ["place", "break", "hit", "step", "fall"]) {
    const soundValue = sound[key];
    if (isRecord(soundValue) && soundValue.name) {
      sounds[key] = String(soundValue.name);
    } else if (typeof soundValue === "string") {
      sounds[key] = soundValue;
    }
  }
  if (Object.keys(sounds).length) {
    settings.sounds = sounds;
  }
  if (furniture.light_level !== undefined && furniture.light_level !== null) {
    settings.light = furniture.light_level;
  }

  const resource = isRecord(item.resource) ? item.resource : {};
  const model = resourceLocation(namespace, resource.model_path);
  const furnitureYOffset = 0.5;
  const element: AnyRecord = { item: ceId, position: `0,${furnitureYOffset},0` };
  if (model) {
    element.model = model;
  }

  const hitbox = isRecord(furniture.hitbox) ? furniture.hitbox : {};
  const hitboxes: AnyRecord[] = [];
  if (Object.keys(hitbox).length) {
    const width = hitbox.width ?? 1;
    const height = Number(hitbox.height ?? 1);
    const length = hitbox.length ?? 1;
    hitboxes.push({
      position: `${hitbox.width_offset ?? 0},${Math.max(height / 2, 0.1) + furnitureYOffset},${hitbox.length_offset ?? 0}`,
      type: "interaction",
      width,
      height,
      length,
      blocks_building: Boolean(furniture.solid ?? false),
      interactive: true,
    });
  }

  const ground: AnyRecord = { elements: [element] };
  if (hitboxes.length) {
    ground.hitboxes = hitboxes;
  }
  if (isRecord(furniture.furniture_sit)) {
    ground.hitboxes ??= [{ position: "0,0,0", type: "interaction" }];
    ground.hitboxes[0].seats = [{ position: `0,${(furniture.furniture_sit.sit_height ?? 0.6) + furnitureYOffset},0` }];
  }

  return { settings, variants: { ground } };
}

function generatedBlockModel(namespace: string, itemId: string, resource: AnyRecord): AnyRecord | null {
  let textures: unknown = resource.textures;
  if (typeof textures === "string") {
    textures = [textures];
  }
  if (!Array.isArray(textures) || textures.length === 0) {
    return null;
  }
  const textureLocations = textures
    .map((texture: unknown) => resourceLocation(namespace, texture))
    .filter((loc: string | null): loc is string => Boolean(loc));
  if (!textureLocations.length) {
    return null;
  }

  const modelPath = resourceLocation(namespace, itemId, "block");
  if (textureLocations.length === 1) {
    return {
      path: modelPath,
      generation: {
        parent: "minecraft:block/cube_all",
        textures: { all: textureLocations[0] },
      },
    };
  }

  const faces = ["down", "up", "north", "east", "south", "west"];
  return {
    path: modelPath,
    generation: {
      parent: "minecraft:block/cube",
      textures: Object.fromEntries(faces.map((face, index) => [face, textureLocations[Math.min(index, textureLocations.length - 1)]])),
    },
  };
}

function convertBlock(namespace: string, itemId: string, item: AnyRecord, block: AnyRecord): AnyRecord {
  const resource = isRecord(item.resource) ? item.resource : {};
  const modelPath = resourceLocation(namespace, resource.model_path);
  const settings: AnyRecord = { item: qualified(namespace, itemId) };
  if (block.hardness !== undefined && block.hardness !== null) {
    settings.hardness = block.hardness;
  }
  if (block.blast_resistance !== undefined && block.blast_resistance !== null) {
    settings.resistance = block.blast_resistance;
  }
  if (block.light_level !== undefined && block.light_level !== null) {
    settings.luminance = block.light_level;
  }

  const placedModel = isRecord(block.placed_model) ? block.placed_model : {};
  const autoState = placedModel.type && String(placedModel.type).toLowerCase().includes("transparent") ? "tripwire" : "note_block";
  const appearance: AnyRecord = { auto_state: autoState };
  if (modelPath) {
    appearance.model = modelPath;
  } else {
    const blockModel = generatedBlockModel(namespace, itemId, resource);
    if (blockModel) {
      appearance.model = blockModel;
    }
  }

  return {
    settings,
    state: appearance,
    loot: {
      pools: [
        {
          rolls: 1,
          entries: [{ type: "item", item: qualified(namespace, itemId) }],
        },
      ],
    },
  };
}

function convertItem(
  namespace: string,
  itemId: string,
  item: AnyRecord,
  converted: AnyRecord,
  report: AnyRecord,
  modelIndex: Set<string>,
): void {
  const resource = isRecord(item.resource) ? item.resource : {};
  const material = vanillaMaterial(resource.material ?? item.material, "paper");
  const ceId = qualified(namespace, itemId);
  const ceItem: AnyRecord = { material };

  const modelId = resource.model_id ?? resource.custom_model_data ?? item.custom_model_data;
  if (modelId !== undefined && modelId !== null) {
    ceItem.custom_model_data = modelId;
  }
  if (item.enabled === false) {
    ceItem.enable = false;
  }

  const name = item.display_name ?? item.name;
  const loreValue = convertLore(item.lore);
  const data: AnyRecord = {};
  if (name !== undefined && name !== null) {
    data.item_name = convertText(name);
  }
  if (loreValue !== null) {
    data.lore = loreValue;
  }
  if (item.unbreakable !== undefined && item.unbreakable !== null) {
    data.unbreakable = Boolean(item.unbreakable);
  }
  if (Object.keys(data).length) {
    ceItem.data = data;
  }

  if (item.category) {
    ceItem.category = item.category;
  }

  const graphics = isRecord(item.graphics) ? item.graphics : {};
  const generate = resource.generate;
  const modelPath = resource.model_path;
  const graphicsModelPath = graphics.model;
  const modelIdLocation = modelPath ? resourceLocation(namespace, modelPath) : null;
  const graphicsModelId = graphicsModelPath ? resourceLocation(namespace, graphicsModelPath) : null;
  if (graphicsModelPath && graphicsModelId && modelIndex.has(graphicsModelId)) {
    ceItem.model = graphicsModelId;
  } else if (generate === false && modelPath && modelIdLocation && modelIndex.has(modelIdLocation)) {
    ceItem.model = modelIdLocation;
  } else {
    Object.assign(ceItem, convertGeneratedModel(namespace, itemId, material, resource));
    if (graphics.texture && isRecord(ceItem.model)) {
      const layer0 = resourceLocation(namespace, graphics.texture);
      ceItem.model.generation ??= {};
      ceItem.model.generation.textures ??= {};
      ceItem.model.generation.textures.layer0 = layer0;
    } else if (graphicsModelPath && isRecord(ceItem.model)) {
      const path = resourceLocation(namespace, graphicsModelPath);
      ceItem.model.path = path;
      ceItem.model.generation ??= {};
      ceItem.model.generation.textures ??= {};
      ceItem.model.generation.textures.layer0 = path;
    } else if (graphics.texture && !("texture" in ceItem) && !("textures" in ceItem)) {
      ceItem.texture = resourceLocation(namespace, graphics.texture);
    }
  }

  const equipment = isRecord(item.equipment) ? item.equipment : {};
  let equipmentSourceId: unknown = null;
  if (Object.keys(equipment).length) {
    equipmentSourceId = equipment.id;
    if (equipmentSourceId) {
      const equipmentId = resourceLocation(namespace, equipmentSourceId);
      ceItem.settings ??= {};
      ceItem.settings.equipment = { asset_id: equipmentId };
      if (idPath(material) === "elytra") {
        let textures = resource.textures;
        if (typeof textures === "string") {
          textures = [textures];
        }
        if (Array.isArray(textures) && textures.length && equipmentId) {
          setConverted(converted, "equipments", equipmentId, {
            type: "component",
            wings: resourceLocation(namespace, textures[0]),
          });
        }
      }
    }
  }
  if (!equipmentSourceId && graphicsModelPath && idPath(material).endsWith("_helmet")) {
    ceItem.data ??= {};
    ceItem.data.equippable ??= {};
    ceItem.data.equippable.slot = "head";
  }

  if (graphics.texture && !("model" in ceItem) && !("texture" in ceItem)) {
    ceItem.texture = resourceLocation(namespace, graphics.texture);
  }

  const mmoitem = isRecord(item.mmoitem) ? item.mmoitem : {};
  if (Object.keys(mmoitem).length) {
    report.external_items.push({
      item: ceId,
      plugin: "MMOItems",
      type: mmoitem.type,
      id: mmoitem.id,
      note: "Left as report only; wire CraftEngine external item data manually if needed.",
    });
  }

  const behaviours = isRecord(item.behaviours) ? item.behaviours : isRecord(item.behaviors) ? item.behaviors : null;
  if (behaviours) {
    if (behaviours.hat === true) {
      ceItem.data ??= {};
      ceItem.data.equippable ??= {};
      ceItem.data.equippable.slot = "head";
    }
    if (isRecord(behaviours.furniture)) {
      const furniture = convertFurniture(namespace, itemId, item, behaviours.furniture);
      setConverted(converted, "furniture", ceId, furniture);
      ceItem.behavior = {
        type: "furniture_item",
        rules: furnitureRulesFromIa(behaviours.furniture),
        furniture: ceId,
      };
    } else if (isRecord(item.specific_properties) && isRecord(item.specific_properties.block)) {
      const block = convertBlock(namespace, itemId, item, item.specific_properties.block);
      setConverted(converted, "blocks", ceId, block);
      ceItem.behavior = { type: "block_item", block: ceId };
    } else {
      const remainingBehaviours = Object.fromEntries(Object.entries(behaviours).filter(([key]) => key !== "hat"));
      if (Object.keys(remainingBehaviours).length) {
        report.unsupported_behaviours.push({ item: ceId, behaviours: remainingBehaviours });
      }
    }
  }

  if (
    isRecord(item.specific_properties) &&
    isRecord(item.specific_properties.block) &&
    !converted.blocks?.[ceId]
  ) {
    const block = convertBlock(namespace, itemId, item, item.specific_properties.block);
    setConverted(converted, "blocks", ceId, block);
    ceItem.behavior = { type: "block_item", block: ceId };
  }

  const supportedItemKeys = new Set([
    "display_name",
    "name",
    "lore",
    "enabled",
    "permission",
    "resource",
    "material",
    "custom_model_data",
    "category",
    "equipment",
    "graphics",
    "mmoitem",
    "behaviours",
    "behaviors",
    "specific_properties",
    "unbreakable",
  ]);
  const unsupportedItemKeys = Object.keys(item)
    .filter((key) => !supportedItemKeys.has(key))
    .sort();
  if (unsupportedItemKeys.length) {
    report.unsupported_item_keys.push({ item: ceId, keys: unsupportedItemKeys });
  }

  setConverted(converted, "items", ceId, ceItem);
}

function convertImages(namespace: string, images: AnyRecord): AnyRecord {
  const converted: AnyRecord = {};
  for (const [imageId, image] of Object.entries(images)) {
    if (!isRecord(image)) {
      continue;
    }
    const scale = image.scale_ratio ?? image.height ?? 10;
    const fallbackAscent = typeof scale === "number" && Number.isInteger(scale) ? Math.max(scale - 1, 0) : 9;
    const yPosition = image.y_position ?? image.ascent ?? fallbackAscent;
    let filePath = resourceLocation(namespace, image.path);
    if (filePath && !filePath.endsWith(".png")) {
      filePath += ".png";
    }
    const ceImage: AnyRecord = {
      height: scale,
      ascent: yPosition,
      font: "minecraft:default",
      file: filePath,
    };
    if (image.symbol !== undefined && image.symbol !== null) {
      ceImage.char = image.symbol;
    } else if (image.char !== undefined && image.char !== null) {
      ceImage.char = image.char;
    }
    converted[qualified(namespace, imageId)] = ceImage;
  }
  return converted;
}

function convertCategories(namespace: string, categories: AnyRecord): AnyRecord {
  const converted: AnyRecord = {};
  for (const [categoryId, category] of Object.entries(categories)) {
    if (!isRecord(category)) {
      continue;
    }
    const ceCategory: AnyRecord = {};
    for (const key of ["priority", "name", "lore", "icon", "hidden", "conditions", "all_items"]) {
      if (key in category) {
        ceCategory[key] = category[key];
      }
    }
    if ("items" in category) {
      ceCategory.list = category.items;
    } else if ("list" in category) {
      ceCategory.list = category.list;
    }
    converted[qualified(namespace, categoryId)] = ceCategory;
  }
  return converted;
}

function convertEquipments(namespace: string, equipments: AnyRecord): AnyRecord {
  const converted: AnyRecord = {};
  for (const [equipmentId, equipment] of Object.entries(equipments)) {
    if (!isRecord(equipment)) {
      continue;
    }
    const ceEquipment: AnyRecord = { type: "component" };
    if (equipment.layer_1) {
      ceEquipment.humanoid = resourceLocation(namespace, equipment.layer_1, "entity/equipment/humanoid");
    }
    if (equipment.layer_2) {
      ceEquipment.humanoid_leggings = resourceLocation(namespace, equipment.layer_2, "entity/equipment/humanoid_leggings");
    }
    for (const key of ["humanoid", "humanoid_leggings", "wings"]) {
      if (key in equipment) {
        ceEquipment[key] = resourceLocation(namespace, equipment[key]);
      }
    }
    converted[qualified(namespace, equipmentId)] = ceEquipment;
  }
  return converted;
}

interface PreparedUpload {
  sourceName: string;
  files: UploadFile[];
}

function prepareUpload(inputFiles: UploadFile[]): PreparedUpload {
  const cleanFiles = inputFiles
    .map((entry) => ({ file: entry.file, path: normalizePath(entry.path) }))
    .filter((entry) => entry.path && !entry.path.endsWith("/"));
  if (!cleanFiles.length) {
    throw new Error("没有可读取的文件。");
  }

  const firstSegments = new Set(cleanFiles.map((entry) => entry.path.split("/")[0]));
  const hasSingleRoot = firstSegments.size === 1 && cleanFiles.every((entry) => entry.path.includes("/"));
  const sourceName = hasSingleRoot ? [...firstSegments][0] : "uploaded_pack";
  const files = cleanFiles
    .map((entry) => ({
      file: entry.file,
      path: hasSingleRoot ? entry.path.split("/").slice(1).join("/") : entry.path,
    }))
    .filter((entry) => entry.path);

  return { sourceName, files };
}

function iterConfigFiles(files: UploadFile[]): UploadFile[] {
  return files
    .filter((entry) => /\.(ya?ml)$/i.test(entry.path))
    .filter((entry) => entry.path.split("/").some((part) => ["config", "configs"].includes(part.toLowerCase())))
    .sort((a, b) => a.path.localeCompare(b.path));
}

function collectModelIndex(files: UploadFile[]): Set<string> {
  const models = new Set<string>();
  for (const entry of files) {
    if (!entry.path.toLowerCase().endsWith(".json")) {
      continue;
    }
    const parts = entry.path.split("/");
    const modelIndex = parts.findIndex((part) => part.toLowerCase() === "models");
    if (modelIndex <= 0 || modelIndex >= parts.length - 1) {
      continue;
    }
    const namespace = parts[modelIndex - 1];
    const modelPath = parts.slice(modelIndex + 1).join("/").replace(/\.json$/i, "");
    models.add(`${normalizeId(namespace)}:${normalizeId(modelPath)}`);
  }
  return models;
}

async function copyResourcepackAssets(files: UploadFile[], zip: JSZip, targetPack: string): Promise<Array<Record<string, string>>> {
  const copied: Array<Record<string, string>> = [];
  const seen = new Set<string>();
  for (const entry of files) {
    const parts = entry.path.split("/");
    const rpIndex = parts.findIndex((part) => part.toLowerCase() === "resourcepack");
    let target: string | null = null;

    if (rpIndex >= 0) {
      const afterRp = parts.slice(rpIndex + 1);
      if (!afterRp.length) {
        continue;
      }
      if (afterRp[0].toLowerCase() === "assets") {
        target = `${targetPack}/resourcepack/assets/${afterRp.slice(1).join("/")}`;
      } else if (afterRp.length === 1) {
        target = `${targetPack}/resourcepack/${afterRp.join("/")}`;
      } else {
        target = `${targetPack}/resourcepack/assets/${afterRp.join("/")}`;
      }
    } else if (parts[0]?.toLowerCase() === "assets") {
      target = `${targetPack}/resourcepack/assets/${parts.slice(1).join("/")}`;
    }

    if (!target || seen.has(target)) {
      continue;
    }
    seen.add(target);
    zip.file(target, entry.file);
    copied.push({ from: entry.path, to: target });
  }
  return copied;
}

function findSourceTexture(files: UploadFile[], namespace: string, texturePath: string): UploadFile | null {
  const expected = `assets/${namespace}/textures/${texturePath}.png`.toLowerCase();
  for (const entry of files) {
    const lower = entry.path.toLowerCase();
    const rpIndex = lower.indexOf("/resourcepack/");
    if (rpIndex >= 0 && lower.slice(rpIndex + "/resourcepack/".length) === expected) {
      return entry;
    }
    if (lower === expected) {
      return entry;
    }
  }
  return null;
}

async function copyGeneratedEquipmentTextures(
  files: UploadFile[],
  zip: JSZip,
  targetPack: string,
  converted: AnyRecord,
): Promise<Array<Record<string, string>>> {
  const copied: Array<Record<string, string>> = [];
  const prefixes: Record<string, string> = {
    humanoid: "entity/equipment/humanoid/",
    humanoid_leggings: "entity/equipment/humanoid_leggings/",
  };

  for (const equipment of Object.values(converted.equipments ?? {})) {
    if (!isRecord(equipment)) {
      continue;
    }
    for (const [key, prefix] of Object.entries(prefixes)) {
      const loc = equipment[key];
      if (typeof loc !== "string" || !loc.includes(":")) {
        continue;
      }
      const [namespace, texturePath] = loc.split(":", 2);
      if (!texturePath.startsWith(prefix)) {
        continue;
      }
      const originalPath = texturePath.slice(prefix.length);
      const source = findSourceTexture(files, namespace, originalPath);
      if (!source) {
        continue;
      }
      const target = `${targetPack}/resourcepack/assets/${namespace}/textures/${texturePath}.png`;
      zip.file(target, source.file);
      copied.push({ from: source.path, to: target });
    }
  }
  return copied;
}

function dumpYaml(data: unknown): string {
  return yaml.dump(data, {
    noRefs: true,
    lineWidth: 120,
    sortKeys: false,
  });
}

function countObjectValues(value: unknown): number {
  return isRecord(value) ? Object.keys(value).length : 0;
}

function addCount(counts: Record<string, number>, key: string, amount = 1): void {
  counts[key] = (counts[key] ?? 0) + amount;
}

export async function migrateSinglePack(inputFiles: UploadFile[], options: MigrationOptions): Promise<MigrationResult> {
  const { sourceName, files } = prepareUpload(inputFiles);
  const modelIndex = collectModelIndex(files);
  const zip = new JSZip();
  const report: AnyRecord = {
    source_pack: sourceName,
    namespace: normalizeId(sourceName),
    config_files: [],
    copied_assets: [],
    counts: {},
    unsupported_top_keys: [],
    unsupported_behaviours: [],
    unsupported_item_keys: [],
    external_items: [],
    yaml_errors: [],
  };
  const convertedByNamespace = new Map<string, AnyRecord>();

  for (const configFile of iterConfigFiles(files)) {
    let data: unknown;
    try {
      const text = (await configFile.file.text()).replace(/^\uFEFF/, "");
      if (/^\s*#/m.test(text) && !text.trim().replace(/#/g, "").trim()) {
        continue;
      }
      data = yaml.load(text);
    } catch (error) {
      report.yaml_errors.push({ file: configFile.path, error: error instanceof Error ? error.message : String(error) });
      continue;
    }
    if (!isRecord(data)) {
      continue;
    }

    const namespace = namespaceFromData(data, sourceName);
    report.namespace = namespace;
    const converted = convertedByNamespace.get(namespace) ?? {};
    convertedByNamespace.set(namespace, converted);
    report.config_files.push({ file: configFile.path, top_keys: Object.keys(data), namespace });

    for (const key of Object.keys(data)) {
      if (key === "info") {
        continue;
      }
      if (!SUPPORTED_CONFIG_KEYS.has(key)) {
        report.unsupported_top_keys.push({ file: configFile.path, key });
      }
    }

    if (isRecord(data.items)) {
      for (const [itemId, item] of Object.entries(data.items)) {
        if (isRecord(item)) {
          convertItem(namespace, itemId, item, converted, report, modelIndex);
          addCount(report.counts, "items");
        }
      }
    }

    if (isRecord(data.font_images)) {
      const images = convertImages(namespace, data.font_images);
      mergeDictOfDicts(converted, "images", images);
      addCount(report.counts, "images", Object.keys(images).length);
    }

    if (isRecord(data.categories)) {
      const categories = convertCategories(namespace, data.categories);
      mergeDictOfDicts(converted, "categories", categories);
      addCount(report.counts, "categories", Object.keys(categories).length);
    }

    if (isRecord(data.equipments)) {
      const equipments = convertEquipments(namespace, data.equipments);
      mergeDictOfDicts(converted, "equipments", equipments);
      addCount(report.counts, "equipments", Object.keys(equipments).length);
    }
  }

  if (!convertedByNamespace.size) {
    throw new Error("没有在 config/configs 目录中找到可转换的 YAML。");
  }

  for (const [namespace, converted] of convertedByNamespace.entries()) {
    const targetPack = namespace;
    if (options.includeAssets) {
      report.copied_assets.push(...(await copyResourcepackAssets(files, zip, targetPack)));
      report.copied_assets.push(...(await copyGeneratedEquipmentTextures(files, zip, targetPack, converted)));
    }

    zip.file(
      `${targetPack}/pack.yml`,
      dumpYaml({
        author: options.packAuthor || "ItemsAdder migration",
        version: options.packVersion || "1.0",
        description: `Converted from ItemsAdder namespace ${namespace}`,
        namespace,
        enable: true,
      }),
    );

    const output: AnyRecord = { _comment: GENERATED_COMMENT };
    for (const key of ["templates", "equipments", "items", "furniture", "blocks", "images", "categories"]) {
      if (isRecord(converted[key]) && Object.keys(converted[key]).length) {
        output[key] = converted[key];
      }
    }

    if (Object.keys(output).length > 1) {
      zip.file(`${targetPack}/configuration/itemsadder_converted.yml`, dumpYaml(output));
      for (const key of Object.keys(output)) {
        if (key !== "_comment") {
          addCount(report.counts, `written_${key}`, countObjectValues(output[key]));
        }
      }
    }
  }

  const totals = { ...report.counts };
  const summary = {
    source: sourceName,
    target: "browser-download",
    dry_run: false,
    packs: 1,
    totals,
    unsupported_top_keys: report.unsupported_top_keys.length,
    unsupported_behaviours: report.unsupported_behaviours.length,
    unsupported_item_keys: report.unsupported_item_keys.length,
    yaml_errors: report.yaml_errors.length,
    reports: [report],
  };
  zip.file("_itemsadder_migration_report.json", JSON.stringify(summary, null, 2));

  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
  return {
    blob,
    fileName: `${normalizeId(sourceName) || "craftengine_pack"}_craftengine.zip`,
    summary,
  };
}
