#!/usr/bin/env python3
r"""
Batch-convert ItemsAdder content packs into CraftEngine resource packs.

Usage:
  python migrate_itemsadder_to_craftengine.py --source D:\server\plugins\ItemsAdder\contents --target D:\server\plugins\CraftEngine\resources
  python migrate_itemsadder_to_craftengine.py --source ... --target ... --dry-run
"""

from __future__ import annotations

import argparse
import copy
import json
import os
import re
import shutil
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import yaml


SUPPORTED_CONFIG_KEYS = {"items", "font_images", "categories", "equipments"}
UNSUPPORTED_CONFIG_KEYS = {
    "entities",
    "recipes",
    "loots",
    "huds",
    "blocks",
    "armors",
    "sounds",
    "menus",
    "worlds_populators",
    "surface_decorators",
    "trees_populators",
    "crops",
    "liquids",
    "vehicles",
}
GENERATED_COMMENT = "Generated by migrate_itemsadder_to_craftengine.py from ItemsAdder."
VANILLA_NAMESPACE = "minecraft"
HANDHELD_SUFFIXES = (
    "_sword",
    "_axe",
    "_pickaxe",
    "_shovel",
    "_hoe",
    "_wand",
    "_staff",
    "_spear",
    "_knife",
    "_hammer",
    "_musket",
    "_paxel",
)


class LiteralStr(str):
    pass


class Dumper(yaml.SafeDumper):
    pass


def _repr_literal(dumper: yaml.SafeDumper, value: LiteralStr) -> yaml.nodes.ScalarNode:
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style="|")


Dumper.add_representer(LiteralStr, _repr_literal)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert ItemsAdder contents into CraftEngine resources."
    )
    parser.add_argument("--source", "-s", required=True, help="ItemsAdder contents directory")
    parser.add_argument("--target", "-t", required=True, help="CraftEngine resources directory")
    parser.add_argument(
        "--pack-author",
        default="ItemsAdder migration",
        help="Author value written to generated pack.yml files",
    )
    parser.add_argument(
        "--pack-version",
        default="1.0",
        help="Version value written to generated pack.yml files",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite generated files and copied assets in target packs",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only scan and report what would be generated",
    )
    parser.add_argument(
        "--no-assets",
        action="store_true",
        help="Do not copy resourcepack/assets files",
    )
    parser.add_argument(
        "--report-name",
        default="_itemsadder_migration_report.json",
        help="Report file name written under the target directory",
    )
    return parser.parse_args()


def load_yaml(path: Path) -> Any | None:
    try:
        text = path.read_text(encoding="utf-8-sig")
    except UnicodeDecodeError:
        text = path.read_text(encoding="utf-8", errors="replace")
    if re.search(r"^\s*#", text) and not text.strip().strip("#").strip():
        return None
    return yaml.safe_load(text)


def dump_yaml(path: Path, data: Any, dry_run: bool, overwrite: bool) -> None:
    if dry_run:
        return
    if path.exists() and not overwrite:
        raise FileExistsError(f"{path} already exists; rerun with --overwrite")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        yaml.dump(
            data,
            Dumper=Dumper,
            allow_unicode=True,
            sort_keys=False,
            width=120,
            default_flow_style=False,
        ),
        encoding="utf-8",
    )


def normalize_id(value: str) -> str:
    value = str(value).strip().replace("\\", "/")
    value = value.removesuffix(".png").removesuffix(".json")
    value = re.sub(r"[^0-9A-Za-z_./:-]+", "_", value)
    value = re.sub(r"_+", "_", value)
    return value.strip("_").lower()


def namespace_from_data(data: Any, fallback: str) -> str:
    if isinstance(data, dict):
        info = data.get("info")
        if isinstance(info, dict) and info.get("namespace"):
            return normalize_id(str(info["namespace"]).replace("/", "_"))
    return normalize_id(fallback.replace("/", "_"))


def qualified(namespace: str, item_id: str) -> str:
    item_id = normalize_id(str(item_id))
    if ":" in item_id:
        return item_id
    return f"{namespace}:{item_id}"


def vanilla_material(value: Any, default: str = "paper") -> str:
    if value is None:
        return default
    material = normalize_id(str(value))
    if ":" in material:
        return material
    return material


def resource_location(namespace: str, value: Any, prefix: str | None = None) -> str | None:
    if value is None:
        return None
    raw = str(value).strip().replace("\\", "/")
    if not raw:
        return None
    raw = raw.removesuffix(".png").removesuffix(".json")
    if ":" in raw:
        ns, path = raw.split(":", 1)
        return f"{normalize_id(ns)}:{normalize_id(path)}"
    path = normalize_id(raw)
    known_roots = (
        "item/",
        "block/",
        "entity/",
        "font/",
        "gui/",
        "models/",
        "textures/",
        "trims/",
        "equipment/",
    )
    if prefix and not path.startswith(prefix.rstrip("/") + "/") and not path.startswith(known_roots):
        path = f"{prefix.rstrip('/')}/{path}"
    return f"{namespace}:{path}"


def infer_parent(material: str, item_id: str) -> str:
    material = material.split(":", 1)[-1]
    item_id = item_id.split(":", 1)[-1]
    if material in {"bow", "crossbow", "fishing_rod"}:
        return f"minecraft:item/{material}"
    if material.endswith(("_sword", "_axe", "_pickaxe", "_shovel", "_hoe", "_trident")):
        return "minecraft:item/handheld"
    if item_id.endswith(HANDHELD_SUFFIXES):
        return "minecraft:item/handheld"
    return "minecraft:item/generated"


def find_content_pack(path: Path, source: Path) -> str:
    rel = path.relative_to(source)
    return rel.parts[0] if rel.parts else path.name


def iter_config_files(source: Path) -> list[Path]:
    config_files: list[Path] = []
    for pattern in ("*.yml", "*.yaml"):
        config_files.extend(source.rglob(pattern))
    return sorted(
        p
        for p in config_files
        if any(part.lower() in {"configs", "config"} for part in p.parts)
    )


def collect_model_index(pack_dir: Path) -> set[str]:
    models: set[str] = set()
    for models_dir in pack_dir.rglob("models"):
        if not models_dir.is_dir():
            continue
        namespace = models_dir.parent.name
        for model_file in models_dir.rglob("*.json"):
            rel = model_file.relative_to(models_dir).as_posix().removesuffix(".json")
            models.add(f"{normalize_id(namespace)}:{normalize_id(rel)}")
    return models


def copy_tree(src: Path, dst: Path, dry_run: bool, overwrite: bool, copied: list[dict[str, str]]) -> None:
    if not src.exists():
        return
    if dry_run:
        copied.append({"from": str(src), "to": str(dst)})
        return
    for item in src.rglob("*"):
        if item.is_dir():
            continue
        rel = item.relative_to(src)
        target = dst / rel
        if target.exists() and not overwrite:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(item, target)
        copied.append({"from": str(item), "to": str(target)})


def copy_resourcepack_assets(source: Path, target_pack: Path, dry_run: bool, overwrite: bool) -> list[dict[str, str]]:
    copied: list[dict[str, str]] = []
    for rp in source.rglob("resourcepack"):
        if not rp.is_dir():
            continue
        assets = rp / "assets"
        if assets.exists():
            copy_tree(assets, target_pack / "resourcepack" / "assets", dry_run, overwrite, copied)
            continue
        for child in rp.iterdir():
            if child.is_dir():
                copy_tree(child, target_pack / "resourcepack" / "assets" / child.name, dry_run, overwrite, copied)
            elif child.is_file():
                copy_tree(rp, target_pack / "resourcepack", dry_run, overwrite, copied)
                break
    direct_assets = source / "assets"
    if direct_assets.exists():
        copy_tree(direct_assets, target_pack / "resourcepack" / "assets", dry_run, overwrite, copied)
    return copied


def find_source_texture(source: Path, namespace: str, texture_path: str) -> Path | None:
    rel = Path("assets") / namespace / "textures" / f"{texture_path}.png"
    for rp in source.rglob("resourcepack"):
        candidate = rp / rel
        if candidate.exists():
            return candidate
    candidate = source / rel
    if candidate.exists():
        return candidate
    return None


def copy_file(src: Path, dst: Path, dry_run: bool, overwrite: bool, copied: list[dict[str, str]]) -> None:
    if dry_run:
        copied.append({"from": str(src), "to": str(dst)})
        return
    if dst.exists() and not overwrite:
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    copied.append({"from": str(src), "to": str(dst)})


def copy_generated_equipment_textures(
    source: Path,
    target_pack: Path,
    converted: dict[str, Any],
    dry_run: bool,
    overwrite: bool,
) -> list[dict[str, str]]:
    copied: list[dict[str, str]] = []
    prefixes = {
        "humanoid": "entity/equipment/humanoid/",
        "humanoid_leggings": "entity/equipment/humanoid_leggings/",
    }
    for equipment in converted.get("equipments", {}).values():
        if not isinstance(equipment, dict):
            continue
        for key, prefix in prefixes.items():
            loc = equipment.get(key)
            if not isinstance(loc, str) or ":" not in loc:
                continue
            namespace, texture_path = loc.split(":", 1)
            if not texture_path.startswith(prefix):
                continue
            original_path = texture_path.removeprefix(prefix)
            src = find_source_texture(source, namespace, original_path)
            if not src:
                continue
            dst = target_pack / "resourcepack" / "assets" / namespace / "textures" / f"{texture_path}.png"
            copy_file(src, dst, dry_run, overwrite, copied)
    return copied


def convert_text(value: Any) -> Any:
    if value is None:
        return None
    return value


def convert_lore(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, list):
        return [convert_text(v) for v in value]
    return [convert_text(value)]


def convert_generated_model(
    namespace: str,
    item_id: str,
    material: str,
    resource: dict[str, Any],
) -> dict[str, Any]:
    textures = resource.get("textures")
    if textures is None and resource.get("texture"):
        textures = [resource.get("texture")]
    if isinstance(textures, str):
        textures = [textures]
    textures = textures if isinstance(textures, list) else []
    texture_locs = [
        resource_location(namespace, texture) for texture in textures if texture is not None
    ]
    texture_locs = [loc for loc in texture_locs if loc]
    if material.split(":", 1)[-1] == "elytra" and len(texture_locs) == 1:
        return {"textures": [texture_locs[0], texture_locs[0]]}
    if len(texture_locs) == 1:
        return {"texture": texture_locs[0]}
    if len(texture_locs) > 1:
        return {"textures": texture_locs}

    path = resource_location(namespace, resource.get("model_path")) or resource_location(namespace, item_id, "item")
    return {
        "model": {
            "type": "minecraft:model",
            "path": path,
            "generation": {
                "parent": infer_parent(material, item_id),
                "textures": {"layer0": path},
            },
        }
    }


def convert_item(
    namespace: str,
    item_id: str,
    item: dict[str, Any],
    converted: dict[str, dict[str, Any]],
    report: dict[str, Any],
    model_index: set[str],
) -> None:
    resource = item.get("resource") if isinstance(item.get("resource"), dict) else {}
    material = vanilla_material(resource.get("material", item.get("material")), "paper")
    ce_id = qualified(namespace, item_id)
    ce_item: dict[str, Any] = {"material": material}

    model_id = resource.get("model_id", resource.get("custom_model_data", item.get("custom_model_data")))
    if model_id is not None:
        ce_item["custom_model_data"] = model_id

    if item.get("enabled") is False:
        ce_item["enable"] = False

    name = item.get("display_name", item.get("name"))
    lore = item.get("lore")
    data: dict[str, Any] = {}
    if name is not None:
        data["item_name"] = convert_text(name)
    lore_value = convert_lore(lore)
    if lore_value is not None:
        data["lore"] = lore_value
    if item.get("unbreakable") is not None:
        data["unbreakable"] = bool(item["unbreakable"])
    if data:
        ce_item["data"] = data

    if item.get("category"):
        ce_item["category"] = item["category"]

    graphics = item.get("graphics") if isinstance(item.get("graphics"), dict) else {}
    generate = resource.get("generate")
    model_path = resource.get("model_path")
    graphics_model_path = graphics.get("model")
    model_id = resource_location(namespace, model_path) if model_path else None
    graphics_model_id = resource_location(namespace, graphics_model_path) if graphics_model_path else None
    if graphics_model_path and graphics_model_id in model_index:
        ce_item["model"] = graphics_model_id
    elif generate is False and model_path and model_id in model_index:
        ce_item["model"] = resource_location(namespace, model_path)
    else:
        ce_item.update(convert_generated_model(namespace, item_id, material, resource))
        if graphics.get("texture") and isinstance(ce_item.get("model"), dict):
            layer0 = resource_location(namespace, graphics.get("texture"))
            ce_item["model"].setdefault("generation", {}).setdefault("textures", {})["layer0"] = layer0
        elif graphics_model_path and isinstance(ce_item.get("model"), dict):
            model_path = resource_location(namespace, graphics_model_path)
            ce_item["model"]["path"] = model_path
            ce_item["model"].setdefault("generation", {}).setdefault("textures", {})["layer0"] = model_path
        elif graphics.get("texture") and "texture" not in ce_item and "textures" not in ce_item:
            ce_item["texture"] = resource_location(namespace, graphics.get("texture"))

    equipment = item.get("equipment") if isinstance(item.get("equipment"), dict) else {}
    eq_id = None
    if equipment:
        eq_id = equipment.get("id")
        if eq_id:
            equipment_id = resource_location(namespace, eq_id)
            ce_item.setdefault("settings", {})["equipment"] = {"asset_id": equipment_id}
            if material.split(":", 1)[-1] == "elytra":
                textures = resource.get("textures")
                if isinstance(textures, str):
                    textures = [textures]
                if isinstance(textures, list) and textures:
                    converted.setdefault("equipments", {})[equipment_id] = {
                        "type": "component",
                        "wings": resource_location(namespace, textures[0]),
                    }
    if not eq_id and graphics_model_path and material.split(":", 1)[-1].endswith("_helmet"):
        ce_item.setdefault("data", {}).setdefault("equippable", {})["slot"] = "head"

    if graphics.get("texture") and "model" not in ce_item and "texture" not in ce_item:
        ce_item["texture"] = resource_location(namespace, graphics.get("texture"))

    mmoitem = item.get("mmoitem") if isinstance(item.get("mmoitem"), dict) else {}
    if mmoitem:
        report["external_items"].append(
            {
                "item": ce_id,
                "plugin": "MMOItems",
                "type": mmoitem.get("type"),
                "id": mmoitem.get("id"),
                "note": "Left as report only; wire CraftEngine external item data manually if needed.",
            }
        )

    behaviours = item.get("behaviours") or item.get("behaviors")
    if isinstance(behaviours, dict):
        if behaviours.get("hat") is True:
            ce_item.setdefault("data", {}).setdefault("equippable", {})["slot"] = "head"
        if isinstance(behaviours.get("furniture"), dict):
            furniture = convert_furniture(namespace, item_id, item, behaviours["furniture"])
            converted.setdefault("furniture", {})[ce_id] = furniture
            ce_item["behavior"] = {
                "type": "furniture_item",
                "rules": furniture_rules_from_ia(behaviours["furniture"]),
                "furniture": ce_id,
            }
        elif isinstance(item.get("specific_properties"), dict) and isinstance(
            item["specific_properties"].get("block"), dict
        ):
            block = convert_block(namespace, item_id, item, item["specific_properties"]["block"])
            converted.setdefault("blocks", {})[ce_id] = block
            ce_item["behavior"] = {"type": "block_item", "block": ce_id}
        else:
            remaining_behaviours = {k: v for k, v in behaviours.items() if k != "hat"}
            if remaining_behaviours:
                report["unsupported_behaviours"].append({"item": ce_id, "behaviours": remaining_behaviours})

    specific = item.get("specific_properties")
    if isinstance(specific, dict) and isinstance(specific.get("block"), dict) and ce_id not in converted.get("blocks", {}):
        block = convert_block(namespace, item_id, item, specific["block"])
        converted.setdefault("blocks", {})[ce_id] = block
        ce_item["behavior"] = {"type": "block_item", "block": ce_id}

    unsupported_item_keys = sorted(
        set(item)
        - {
            "display_name",
            "name",
            "lore",
            "enabled",
            "permission",
            "resource",
            "material",
            "custom_model_data",
            "category",
            "equipment",
            "graphics",
            "mmoitem",
            "behaviours",
            "behaviors",
            "specific_properties",
            "unbreakable",
        }
    )
    if unsupported_item_keys:
        report["unsupported_item_keys"].append({"item": ce_id, "keys": unsupported_item_keys})

    converted.setdefault("items", {})[ce_id] = ce_item


def furniture_rules_from_ia(furniture: dict[str, Any]) -> dict[str, Any]:
    placeable = furniture.get("placeable_on") if isinstance(furniture.get("placeable_on"), dict) else {}
    rules: dict[str, Any] = {}
    if placeable.get("floor", True):
        rules["ground"] = {"rotation": "four", "alignment": "center"}
    if placeable.get("walls"):
        rules["wall"] = {"rotation": "any", "alignment": "center"}
    if placeable.get("ceiling"):
        rules["ceiling"] = {"rotation": "four", "alignment": "center"}
    return rules or {"ground": {"rotation": "four", "alignment": "center"}}


def convert_furniture(
    namespace: str,
    item_id: str,
    item: dict[str, Any],
    furniture: dict[str, Any],
) -> dict[str, Any]:
    ce_id = qualified(namespace, item_id)
    sound = furniture.get("sound") if isinstance(furniture.get("sound"), dict) else {}
    settings: dict[str, Any] = {"item": ce_id}
    sounds: dict[str, Any] = {}
    for key in ("place", "break", "hit", "step", "fall"):
        sound_value = sound.get(key)
        if isinstance(sound_value, dict) and sound_value.get("name"):
            sounds[key] = str(sound_value["name"]).replace(".", ".")
        elif isinstance(sound_value, str):
            sounds[key] = sound_value
    if sounds:
        settings["sounds"] = sounds
    if furniture.get("light_level") is not None:
        settings["light"] = furniture["light_level"]

    resource = item.get("resource") if isinstance(item.get("resource"), dict) else {}
    model = resource_location(namespace, resource.get("model_path"))
    furniture_y_offset = 0.5
    element = {"item": ce_id, "position": f"0,{furniture_y_offset},0"}
    if model:
        element["model"] = model

    hitbox = furniture.get("hitbox") if isinstance(furniture.get("hitbox"), dict) else {}
    hitboxes: list[dict[str, Any]] = []
    if hitbox:
        width = hitbox.get("width", 1)
        height = hitbox.get("height", 1)
        length = hitbox.get("length", 1)
        hitboxes.append(
            {
                "position": f"{hitbox.get('width_offset', 0)},{max(float(height) / 2, 0.1) + furniture_y_offset},{hitbox.get('length_offset', 0)}",
                "type": "interaction",
                "width": width,
                "height": height,
                "length": length,
                "blocks_building": bool(furniture.get("solid", False)),
                "interactive": True,
            }
        )

    ground: dict[str, Any] = {"elements": [element]}
    if hitboxes:
        ground["hitboxes"] = hitboxes
    if "furniture_sit" in furniture and isinstance(furniture["furniture_sit"], dict):
        ground.setdefault("hitboxes", hitboxes or [{"position": "0,0,0", "type": "interaction"}])
        ground["hitboxes"][0]["seats"] = [
            {"position": f"0,{furniture['furniture_sit'].get('sit_height', 0.6) + furniture_y_offset},0"}
        ]

    return {"settings": settings, "variants": {"ground": ground}}


def convert_block(namespace: str, item_id: str, item: dict[str, Any], block: dict[str, Any]) -> dict[str, Any]:
    resource = item.get("resource") if isinstance(item.get("resource"), dict) else {}
    model_path = resource_location(namespace, resource.get("model_path"))
    settings: dict[str, Any] = {
        "item": qualified(namespace, item_id),
    }
    if block.get("hardness") is not None:
        settings["hardness"] = block["hardness"]
    if block.get("blast_resistance") is not None:
        settings["resistance"] = block["blast_resistance"]
    if block.get("light_level") is not None:
        settings["luminance"] = block["light_level"]

    auto_state = "note_block"
    placed_model = block.get("placed_model") if isinstance(block.get("placed_model"), dict) else {}
    if placed_model.get("type") and "transparent" in str(placed_model.get("type")).lower():
        auto_state = "tripwire"

    appearance: dict[str, Any] = {"auto_state": auto_state}
    if model_path:
        appearance["model"] = model_path
    else:
        block_model = generated_block_model(namespace, item_id, resource)
        if block_model:
            appearance["model"] = block_model
    ce_block: dict[str, Any] = {
        "settings": settings,
        "state": appearance,
        "loot": {
            "pools": [
                {
                    "rolls": 1,
                    "entries": [{"type": "item", "item": qualified(namespace, item_id)}],
                }
            ]
        },
    }
    return ce_block


def generated_block_model(namespace: str, item_id: str, resource: dict[str, Any]) -> dict[str, Any] | None:
    textures = resource.get("textures")
    if isinstance(textures, str):
        textures = [textures]
    if not isinstance(textures, list) or not textures:
        return None
    texture_locs = [resource_location(namespace, texture) for texture in textures if texture is not None]
    texture_locs = [loc for loc in texture_locs if loc]
    if not texture_locs:
        return None
    model_path = resource_location(namespace, item_id, "block")
    if len(texture_locs) == 1:
        return {
            "path": model_path,
            "generation": {
                "parent": "minecraft:block/cube_all",
                "textures": {"all": texture_locs[0]},
            },
        }
    faces = ["down", "up", "north", "east", "south", "west"]
    return {
        "path": model_path,
        "generation": {
            "parent": "minecraft:block/cube",
            "textures": {
                face: texture_locs[min(index, len(texture_locs) - 1)]
                for index, face in enumerate(faces)
            },
        },
    }


def convert_images(namespace: str, images: dict[str, Any]) -> dict[str, Any]:
    converted: dict[str, Any] = {}
    for image_id, image in images.items():
        if not isinstance(image, dict):
            continue
        scale = image.get("scale_ratio", image.get("height", 10))
        y_position = image.get("y_position", image.get("ascent", max(int(scale) - 1 if isinstance(scale, int) else 9, 0)))
        file_path = resource_location(namespace, image.get("path"))
        if file_path and not file_path.endswith(".png"):
            file_path += ".png"
        ce_image = {
            "height": scale,
            "ascent": y_position,
            "font": image.get("font", f"{namespace}:default"),
            "file": file_path,
        }
        if image.get("symbol") is not None:
            ce_image["char"] = image["symbol"]
        elif image.get("char") is not None:
            ce_image["char"] = image["char"]
        converted[qualified(namespace, image_id)] = ce_image
    return converted


def convert_categories(namespace: str, categories: dict[str, Any]) -> dict[str, Any]:
    converted: dict[str, Any] = {}
    for category_id, category in categories.items():
        if not isinstance(category, dict):
            continue
        ce_category: dict[str, Any] = {}
        for key in ("priority", "name", "lore", "icon", "hidden", "conditions", "all_items"):
            if key in category:
                ce_category[key] = category[key]
        if "items" in category:
            ce_category["list"] = category["items"]
        elif "list" in category:
            ce_category["list"] = category["list"]
        converted[qualified(namespace, category_id)] = ce_category
    return converted


def convert_equipments(namespace: str, equipments: dict[str, Any]) -> dict[str, Any]:
    converted: dict[str, Any] = {}
    for equipment_id, equipment in equipments.items():
        if not isinstance(equipment, dict):
            continue
        ce_equipment: dict[str, Any] = {"type": "component"}
        if equipment.get("layer_1"):
            ce_equipment["humanoid"] = resource_location(namespace, equipment["layer_1"], "entity/equipment/humanoid")
        if equipment.get("layer_2"):
            ce_equipment["humanoid_leggings"] = resource_location(
                namespace, equipment["layer_2"], "entity/equipment/humanoid_leggings"
            )
        for key in ("humanoid", "humanoid_leggings", "wings"):
            if key in equipment:
                ce_equipment[key] = resource_location(namespace, equipment[key])
        converted[qualified(namespace, equipment_id)] = ce_equipment
    return converted


def merge_dict_of_dicts(target: dict[str, Any], key: str, values: dict[str, Any]) -> None:
    if not values:
        return
    target.setdefault(key, {}).update(values)


def write_pack_yml(target_pack: Path, namespace: str, args: argparse.Namespace) -> None:
    pack = {
        "author": args.pack_author,
        "version": args.pack_version,
        "description": f"Converted from ItemsAdder namespace {namespace}",
        "namespace": namespace,
        "enable": True,
    }
    dump_yaml(target_pack / "pack.yml", pack, args.dry_run, args.overwrite)


def process_content_pack(pack_dir: Path, source_root: Path, target_root: Path, args: argparse.Namespace) -> dict[str, Any]:
    report: dict[str, Any] = {
        "source_pack": str(pack_dir),
        "namespace": normalize_id(pack_dir.name),
        "config_files": [],
        "copied_assets": [],
        "counts": Counter(),
        "unsupported_top_keys": [],
        "unsupported_behaviours": [],
        "unsupported_item_keys": [],
        "external_items": [],
        "yaml_errors": [],
    }
    converted_by_namespace: dict[str, dict[str, Any]] = defaultdict(dict)
    model_index = collect_model_index(pack_dir)

    for config_file in iter_config_files(pack_dir):
        try:
            data = load_yaml(config_file)
        except Exception as exc:
            report["yaml_errors"].append({"file": str(config_file), "error": str(exc)})
            continue
        if not isinstance(data, dict):
            continue
        namespace = namespace_from_data(data, pack_dir.name)
        report["namespace"] = namespace
        converted = converted_by_namespace[namespace]
        rel_config = config_file.relative_to(pack_dir)
        file_record = {"file": str(rel_config), "top_keys": list(data.keys()), "namespace": namespace}
        report["config_files"].append(file_record)

        for key in data:
            if key == "info":
                continue
            if key not in SUPPORTED_CONFIG_KEYS:
                report["unsupported_top_keys"].append({"file": str(rel_config), "key": key})

        if isinstance(data.get("items"), dict):
            for item_id, item in data["items"].items():
                if isinstance(item, dict):
                    convert_item(namespace, item_id, item, converted, report, model_index)
                    report["counts"]["items"] += 1

        if isinstance(data.get("font_images"), dict):
            images = convert_images(namespace, data["font_images"])
            merge_dict_of_dicts(converted, "images", images)
            report["counts"]["images"] += len(images)

        if isinstance(data.get("categories"), dict):
            categories = convert_categories(namespace, data["categories"])
            merge_dict_of_dicts(converted, "categories", categories)
            report["counts"]["categories"] += len(categories)

        if isinstance(data.get("equipments"), dict):
            equipments = convert_equipments(namespace, data["equipments"])
            merge_dict_of_dicts(converted, "equipments", equipments)
            report["counts"]["equipments"] += len(equipments)

    for namespace, converted in converted_by_namespace.items():
        target_pack = target_root / namespace
        if not args.no_assets:
            report["copied_assets"].extend(copy_resourcepack_assets(pack_dir, target_pack, args.dry_run, args.overwrite))
            report["copied_assets"].extend(
                copy_generated_equipment_textures(pack_dir, target_pack, converted, args.dry_run, args.overwrite)
            )
        write_pack_yml(target_pack, namespace, args)
        output: dict[str, Any] = {"_comment": GENERATED_COMMENT}
        for key in ("templates", "equipments", "items", "furniture", "blocks", "images", "categories"):
            if key in converted and converted[key]:
                output[key] = converted[key]
        if len(output) > 1:
            dump_yaml(
                target_pack / "configuration" / "itemsadder_converted.yml",
                output,
                args.dry_run,
                args.overwrite,
            )
            for key in output:
                if key != "_comment":
                    report["counts"][f"written_{key}"] += len(output[key])

    report["counts"] = dict(report["counts"])
    return report


def write_report(target: Path, report_name: str, report: dict[str, Any], dry_run: bool, overwrite: bool) -> None:
    if dry_run:
        return
    target.mkdir(parents=True, exist_ok=True)
    report_path = target / report_name
    if report_path.exists() and not overwrite:
        stem = report_path.stem
        suffix = report_path.suffix
        idx = 1
        while (target / f"{stem}.{idx}{suffix}").exists():
            idx += 1
        report_path = target / f"{stem}.{idx}{suffix}"
    report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")


def main() -> int:
    args = parse_args()
    source = Path(args.source).resolve()
    target = Path(args.target).resolve()
    if not source.exists() or not source.is_dir():
        raise SystemExit(f"Source directory does not exist: {source}")
    if args.dry_run:
        print(f"DRY RUN: scanning {source} -> {target}")
    elif target.exists() and not target.is_dir():
        raise SystemExit(f"Target path exists and is not a directory: {target}")

    all_reports: list[dict[str, Any]] = []
    content_dirs = sorted(p for p in source.iterdir() if p.is_dir())
    for pack_dir in content_dirs:
        report = process_content_pack(pack_dir, source, target, args)
        all_reports.append(report)

    summary = {
        "source": str(source),
        "target": str(target),
        "dry_run": bool(args.dry_run),
        "packs": len(all_reports),
        "totals": dict(sum((Counter(r["counts"]) for r in all_reports), Counter())),
        "unsupported_top_keys": sum(len(r["unsupported_top_keys"]) for r in all_reports),
        "unsupported_behaviours": sum(len(r["unsupported_behaviours"]) for r in all_reports),
        "unsupported_item_keys": sum(len(r["unsupported_item_keys"]) for r in all_reports),
        "yaml_errors": sum(len(r["yaml_errors"]) for r in all_reports),
        "reports": all_reports,
    }

    write_report(target, args.report_name, summary, args.dry_run, args.overwrite)
    print(json.dumps({k: v for k, v in summary.items() if k != "reports"}, ensure_ascii=False, indent=2))
    if args.dry_run:
        print("Dry run complete; rerun without --dry-run to write files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
